name: Test SSH Secrets

on:
  push:
    branches:
      - production

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets (masked)
        run: |
          echo "EC2_HOST is set: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER is set: ${{ secrets.EC2_USER }}"
          echo "EC2_SSH_KEY is set: ${# secrets.EC2_SSH_KEY > 0 ? 'Yes' : 'No'}"
